### ISSUE TITLE
[FR] Include highlighted text

### ISSUE THREAD

**Issue by Chykg0** [leschuster/obsidian-advanced-copy#9]
Hello, thank your for your plugin, i think it's a great idea.

I tried your plugin with the command "copy markdown to html" and it works well, but the only thing maybe is missing is the handle of the hilighted text with "==" exemple : ==TEXT== .
I don't think te plugin actually transform this kind of modification, but maybe i'm missing something (and to be honest i'm not really a technical person so i tried to have look on the settings but didn't see anything).

That's all for me, thank's for this plugin.

**Comment by leschuster** [comment]
Hello @Chykg0,

you are right. I totally forgot that highlights are a thing in Obsidian. I'll try to add this as soon as possible. 

Thank you for reaching out.

**Comment by leschuster** [comment]
@Chykg0 I have just released version 0.5.0, which includes support for highlights. As an existing user, you may receive a warning prompting you to configure the new setting.
